name: Check Team Membership
description: A GitHub Action to check if a user is a member of a specified team in an organization using the GitHub API
author: Lee Lott

inputs:
  user:
    description: 'The GitHub username to check for team membership'
    required: true
  team-slug:
    description: 'The slug of the team to check membership against'
    required: true
  token:
    description: 'GitHub token with organization read access'
    required: true
  owner:
    description: 'The owner of the organization (user or organization)'
    required: true

outputs:
  result:
    description: 'Result of the action ("success" or "failure")'
    value: ${{ steps.action.outputs.result }}
  is-member:
    description: 'Boolean indicating if the user is a member of the team (true for HTTP 200, false otherwise)'
    value: ${{ steps.action.outputs.is-member }}
  error-message:
    description: 'Error message if the user is not a member of the team'
    value: ${{ steps.action.outputs.error-message }}

runs:
  using: composite
  steps:
    - name: Check Team Membership
      id: action
      run: |        
        source ${{ github.action_path }}/action.sh
        check_approver_membership "${{ inputs.user }}" "${{ inputs.team-slug }}" "${{ inputs.token }}" "${{ inputs.owner }}"
      shell: bash
